apiVersion: v2
name: cloud-ninjas-project
description: A Helm chart for the Cloud Ninjas project
type: application
version: 0.1.0
appVersion: "1.1"
maintainers:
  - name: Mohamed Mahmoud
    email: mohamedmahmouddesouky@gmail.com